---
title: "Molecular Detection of the -308 G/A Polymorphism in the Tumor Necrosis Factor Alpha (TNFα) Gene Promoter and its Relationship with the Development of Severe Dengue in Patients from Urabá Subregion, Antioquia-Colombia"
format: html
editor: visual
---

```{r}
#install.packages("logistf")
library(readxl)
library(dplyr)
library(logistf)

# Load dataset
datos <- read_excel("Dengue.xls")
View(datos)

# Remove any leading or trailing spaces from names.
names(datos) <- trimws(names(datos))

# Check names.
names(datos)

attach(datos)

# Check the variables. 
table(tipo, useNA = "ifany")
table(Genotipo, useNA = "ifany")
table(primaria_1, useNA = "ifany")
table(serotipo, useNA = "ifany")

summary(edad)
```

```{r}
#Univariate analysis.
#Table 1

datos <- datos %>%
  mutate(
    grupo = case_when(
      tipo == "Dengue" ~ "DWOS",
      tipo == "Dengue with warning signs" ~ "DWWS",
      tipo == "Severe dengue" ~ "SD"
    ),
    grupo = factor(grupo, levels = c("DWOS", "DWWS", "SD")),
    
    woman_1 = as.factor(woman_1),
    rural_1 = as.factor(rural_1),
    seguridad = as.factor(seguridad),
    educacion = as.factor(educacion)
  )
table(datos$tipo)
table(datos$grupo)
```

```{r}
#Table 1
tabla1 <- datos %>%
  select(grupo, edad, woman_1, rural_1, seguridad, educacion) %>%
  tbl_summary(
    by = grupo,
    type = edad ~ "continuous2",
    statistic = list(
      edad ~ c(
        "{mean} / {sd}",
        "{median} ({p25}–{p75})"
      ),
      all_categorical() ~ "{n} ({p}%)"
    ),
    missing = "ifany"
  ) %>%
  add_p(
    test = list(
      edad ~ "kruskal.test",
      educacion ~ "fisher.test"
    )
  ) %>%
  bold_labels()

tabla1
```

```{r}
#Bivariate analysis

datos <- datos %>%
  mutate(
    comorbilidad = factor(comorbilidad, c(0,1), c("No","Yes")),
    infeccion = factor(primaria_1, c(1,0), c("Primary","Secondary")),
    coinfeccion = factor(coinfeccion_1, c(0,1), c("No","Yes"))
  )
```

```{r}
#Table 2
tabla2 <- datos %>%
  select(
    grupo,
    comorbilidad, infeccion, coinfeccion,
    dolor_retro, dolor_abdo, nauseas, fatiga, mareo,
    mialgias, artralgias, exantema, edema_extre,
    acumulacion_liquidos, ascitis, irritabilidad,
    hepatomegalia, esplenomegalia, hematemesis
  ) %>%
  tbl_summary(
    by = grupo,
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "ifany"
  ) %>%
  add_p() %>%
  bold_labels()

tabla2
```

```{r}
library(dplyr)
library(gtsummary)

vars_lab <- c(
  "PA_Sistolica",
  "PA_Diastolica",
  "Presion_Arterial_Media(PAM)1",
  "Presion_de_pulso1",
  "Frecuencia_cardiaca",
  "Frecuencia_Respiratoria",
  "Saturacion2",
  "Hemoglobina",
  "Hematocrito",
  "Recuento_plaquetas",
  "LeucocitosWBC",
  "%Neutrofilos",
  "%Linfocitos",
  "%eosinofilos",
  "%basofilos",
  "AST(UI/L)",
  "ALT(UI/L)",
  "Proteina_C_Reactiva",
  "Creatinina",
  "BUN",
  "TP",
  "TTP"
)

datos <- datos %>%
  mutate(
    across(
      all_of(vars_lab),
      ~ as.numeric(as.character(.))
    )
  )

sapply(datos[vars_lab], class)
```

```{r}
# Normalidad por variable y grupo
normales <- vars[sapply(vars, function(v)
  all(by(datos[[v]], datos$grupo,
         function(x) shapiro.test(na.omit(x))$p.value > 0.05))
)]

no_normales <- setdiff(vars, normales)

normales
no_normales

anova_welch <- function(data, variable, by, ...) {
  d <- data.frame(y = data[[variable]], g = data[[by]])
  broom::tidy(oneway.test(y ~ g, data = d))
}
```

```{r}
anova <- c(
  "Frecuencia_cardiaca",
  "%Neutrofilos",
  "%Linfocitos",
  "TTP"
)

kruskal <- setdiff(vars, anova)
```

```{r}

library(dplyr)
library(tidyr)
library(gtsummary)

# Variables de la Tabla 3
vars <- c(
  "PA_Sistolica","PA_Diastolica","Presion_Arterial_Media(PAM)1",
  "Presion_de_pulso1","Frecuencia_cardiaca","Frecuencia_Respiratoria",
  "Saturacion2","Hemoglobina","Hematocrito","Recuento_plaquetas",
  "LeucocitosWBC","%Neutrofilos","%Linfocitos","%eosinofilos",
  "%basofilos","AST(UI/L)","ALT(UI/L)","Proteina_C_Reactiva",
  "Creatinina","BUN","TP","TTP"
)

# Normalidad por grupo
normales <- vars[sapply(vars, function(v)
  all(tapply(
    datos[[v]], datos$grupo,
    function(x) shapiro.test(na.omit(x))$p.value > 0.05
  ))
)]

no_normales <- setdiff(vars, normales)

# p-valores ANOVA
p_anova <- datos %>%
  select(grupo, all_of(normales)) %>%
  pivot_longer(-grupo, names_to = "variable", values_to = "valor") %>%
  filter(!is.na(valor)) %>%
  group_by(variable) %>%
  summarise(
    p.value = summary(aov(valor ~ grupo))[[1]][["Pr(>F)"]][1],
    Test = "ANOVA",
    .groups = "drop"
  )

# p-valores Kruskal-Wallis
p_kruskal <- datos %>%
  select(grupo, all_of(no_normales)) %>%
  pivot_longer(-grupo, names_to = "variable", values_to = "valor") %>%
  filter(!is.na(valor)) %>%
  group_by(variable) %>%
  summarise(
    p.value = kruskal.test(valor ~ grupo)$p.value,
    Test = "Kruskal-Wallis",
    .groups = "drop"
  )

pruebas <- bind_rows(p_anova, p_kruskal)

# Tabla 3
tabla3 <- datos %>%
  select(grupo, all_of(vars)) %>%
  tbl_summary(
    by = grupo,
    type = all_of(vars) ~ "continuous",
    statistic = all_continuous() ~ "{median} ({IQR})",
    digits = all_continuous() ~ 1,
    missing = "no",
    label = list(
      PA_Sistolica ~ "Systolic Blood Pressure (SBP)",
      PA_Diastolica ~ "Diastolic Blood Pressure (DBP)",
      `Presion_Arterial_Media(PAM)1` ~ "Mean Arterial Pressure (MAP)",
      Presion_de_pulso1 ~ "Pulse Pressure",
      Frecuencia_cardiaca ~ "Heart Rate (HR)",
      Frecuencia_Respiratoria ~ "Respiratory Rate (RR)",
      Saturacion2 ~ "Oxygen Saturation (SatO2)",
      Hemoglobina ~ "Hemoglobin",
      Hematocrito ~ "Hematocrit",
      Recuento_plaquetas ~ "Platelet Count",
      LeucocitosWBC ~ "White Blood Cell Count (WBC)",
      `%Neutrofilos` ~ "Neutrophils",
      `%Linfocitos` ~ "Lymphocytes",
      `%eosinofilos` ~ "Eosinophils",
      `%basofilos` ~ "Basophils",
      `AST(UI/L)` ~ "Aspartate Aminotransferase (AST)",
      `ALT(UI/L)` ~ "Alanine Aminotransferase (ALT)",
      Proteina_C_Reactiva ~ "C-Reactive Protein (CRP)",
      Creatinina ~ "Creatinine",
      BUN ~ "Blood Urea Nitrogen (BUN)",
      TP ~ "Prothrombin Time (PT)",
      TTP ~ "Activated Partial Thromboplastin Time (aPTT)"
    )
  ) %>%
  modify_table_body(
    ~ .x %>%
      left_join(pruebas, by = "variable") %>%
      relocate(Test, .before = p.value)
  ) %>%
  modify_fmt_fun(
    p.value ~ function(x) style_pvalue(x, digits = 3)
  ) %>%
  modify_header(
    Test ~ "**Test**",
    p.value ~ "**p-value**"
  )

tabla3
```

```{r}
#Prepare data for regression.

library(dplyr)
library(logistf)

datos <- datos %>%
  mutate(
    # Desenlace: 1 = dengue grave; 0 = no grave
    severo = ifelse(tipo == "Severe dengue", 1, 0),
    
    # Exposición: cualquier genotipo mutante
    mutacion = ifelse(Genotipo == "Wild-type", 0, 1),
    
    # 1 = infección secundaria
    # En la base primaria_1: 1 = primaria, 0 = secundaria
    secundaria = case_when(
      primaria_1 == 0 ~ 1,
      primaria_1 == 1 ~ 0,
      TRUE ~ NA_real_
    )
  )
```

```{r}
#Prepare data for regression.

table(datos$severo, useNA = "ifany")
table(datos$mutacion, useNA = "ifany")
table(datos$secundaria, useNA = "ifany")

table(datos$mutacion, datos$severo)
table(datos$secundaria, datos$severo)

```

```{r}
#Prepare data for regression.
table(datos$mutacion, datos$secundaria, useNA = "ifany")
datos %>%
  filter(mutacion == 1) %>%
  select(tipo, edad, primaria_1, secundaria, Genotipo, serotipo)
```

```{r}
#Unadjusted model / Firth logistic regression.

modelo_crudo <- logistf(
  severo ~ mutacion,
  data = datos
)

summary(modelo_crudo)
```

```{r}
#Age-adjusted model / per 10-year increase in age...

datos <- datos %>%
  mutate(
    edad10 = edad / 10
  )

modelo_edad <- logistf(
  severo ~ mutacion + edad10,
  data = datos
)

summary(modelo_edad)
```

```{r}
#Age-adjusted model / per 10-year increase in age...
resultado_edad_ajustado <- data.frame(
  Variable = names(coef(modelo_edad)),
  OR = exp(coef(modelo_edad)),
  LI95 = exp(modelo_edad$ci.lower),
  LS95 = exp(modelo_edad$ci.upper),
  p = modelo_edad$prob
)

resultado_edad_ajustado
```

```{r}
#Sensitivity analysis model: age + infection

modelo_ajustado <- logistf(
  severo ~ mutacion + edad10 + secundaria,
  data = datos
)

summary(modelo_ajustado)
```

```{r}
#Table 
datos_modelo <- datos %>%
  select(severo, mutacion, edad10, secundaria) %>%
  filter(complete.cases(.))

nrow(datos_modelo)

table(datos_modelo$severo)
table(datos_modelo$mutacion)
table(datos_modelo$secundaria)
```

```{r}
#Table
resultado_ajustado <- data.frame(
  Variable = names(coef(modelo_ajustado)),
  OR = exp(coef(modelo_ajustado)),
  LI95 = exp(modelo_ajustado$ci.lower),
  LS95 = exp(modelo_ajustado$ci.upper),
  p = modelo_ajustado$prob
)

resultado_ajustado
```

```{r}
#Compare the three regression analyses.

comparacion <- data.frame(
  Modelo = c(
    "Crude",
    "Adjusted for age",
    "Adjusted for age and secondary infection"
  ),
  
  OR = c(
    exp(coef(modelo_crudo)["mutacion"]),
    exp(coef(modelo_edad)["mutacion"]),
    exp(coef(modelo_ajustado)["mutacion"])
  ),
  
  LI95 = c(
    exp(modelo_crudo$ci.lower["mutacion"]),
    exp(modelo_edad$ci.lower["mutacion"]),
    exp(modelo_ajustado$ci.lower["mutacion"])
  ),
  
  LS95 = c(
    exp(modelo_crudo$ci.upper["mutacion"]),
    exp(modelo_edad$ci.upper["mutacion"]),
    exp(modelo_ajustado$ci.upper["mutacion"])
  ),
  
  p = c(
    modelo_crudo$prob["mutacion"],
    modelo_edad$prob["mutacion"],
    modelo_ajustado$prob["mutacion"]
  )
)

comparacion %>%
  mutate(
    OR = round(OR, 2),
    LI95 = round(LI95, 2),
    LS95 = round(LS95, 2),
    p = round(p, 3)
  )
```

```{r}
#SD vs DWOS
library(dplyr)
library(logistf)

datos_SD_DWOS <- datos %>%
  filter(tipo %in% c("Severe dengue", "Dengue")) %>%
  mutate(
    desenlace = ifelse(tipo == "Severe dengue", 1, 0),
    edad10 = edad / 10
  )

modelo_SD_DWOS <- logistf(
  desenlace ~ mutacion + edad10 + secundaria,
  data = datos_SD_DWOS
)

summary(modelo_SD_DWOS)
```

```{r}
#SD vs DWWS
datos_SD_DWWS <- datos %>%
  filter(tipo %in% c("Severe dengue",
                     "Dengue with warning signs")) %>%
  mutate(
    desenlace = ifelse(tipo == "Severe dengue", 1, 0),
    edad10 = edad / 10
  )

modelo_SD_DWWS <- logistf(
  desenlace ~ mutacion + edad10 + secundaria,
  data = datos_SD_DWWS
)

summary(modelo_SD_DWWS)
```

```{r}
#DWWS vs DWOS
datos_DWWS_DWOS <- datos %>%
  filter(tipo %in% c("Dengue with warning signs", "Dengue")) %>%
  mutate(
    desenlace = ifelse(tipo == "Dengue with warning signs", 1, 0),
    edad10 = edad / 10
  )

modelo_DWWS_DWOS <- logistf(
  desenlace ~ mutacion + edad10 + secundaria,
  data = datos_DWWS_DWOS
)

summary(modelo_DWWS_DWOS)
```

```{r}
extraer_mutacion <- function(modelo, comparacion) {
  data.frame(
    Comparacion = comparacion,
    aOR = exp(coef(modelo)["mutacion"]),
    LI95 = exp(modelo$ci.lower["mutacion"]),
    LS95 = exp(modelo$ci.upper["mutacion"]),
    p = modelo$prob["mutacion"]
  )
}

resultados_pares <- bind_rows(
  extraer_mutacion(modelo_SD_DWOS, "SD vs DWOS"),
  extraer_mutacion(modelo_SD_DWWS, "SD vs DWWS"),
  extraer_mutacion(modelo_DWWS_DWOS, "DWWS vs DWOS")
)

resultados_pares %>%
  mutate(
    aOR = round(aOR, 2),
    LI95 = round(LI95, 2),
    LS95 = round(LS95, 2),
    p = round(p, 3)
  )
```
